name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Cache Yarn dependencies
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
          ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies
      run: yarn install
      shell: bash

    - name: Verify Node.js Version
      run: node -v
      shell: bash
